<section class="link-back page__inner">
    <a class="link-back__btn" href="/">Home</a>
    <span class="mx-0-5">></span> Blog
</section>

<section class="page__inner page__section grid grid--col-1-3">
    <div>
        <div class="mb-2">
            <h3 class="title-2">Search</h3>
            <div class="pos-rel">
                <input class="input" type="text" placeholder="Search...">
                <button class="btn btn__input btn--bg-black" type="submit"><i class="fas fa-search"></i></button>
            </div>
        </div>

        <div class="mb-2">
            <h3 class="title-2">Categories</h3>

            <ul>
                <li><a class="link--block" href="#">Fashion</a></li>
                <li><a class="link--block" href="#">Travel</a></li>
                <li><a class="link--block" href="#">Picnic</a></li>
                <li><a class="link--block" href="#">Model</a></li>
            </ul>
        </div>

        <div class="mb-2">
            <h3 class="title-2">Recent Post</h3>

            <a class="grid grid--gap-1 grid--icon my-1" href="#">
                <img src="img/blog/recent-1.jpg">
                <div>
                    <h4>The personality trait that makes...</h4>
                    <p class="blog__date"><span class="blog__categorie">Fashion</span> - May 19, 2019</p>
                </div>
            </a>

            <a class="grid grid--gap-1 grid--icon my-1" href="#">
                <img src="img/blog/recent-2.jpg">
                <div>
                    <h4>The personality trait that makes...</h4>
                    <p class="blog__date"><span class="blog__categorie">Fashion</span> - May 19, 2019</p>
                </div>
            </a>

            <a class="grid grid--gap-1 grid--icon my-1" href="#">
                <img src="img/blog/recent-3.jpg">
                <div>
                    <h4>The personality trait that makes...</h4>
                    <p class="blog__date"><span class="blog__categorie">Fashion</span> - May 19, 2019</p>
                </div>
            </a>

            <a class="grid grid--gap-1 grid--icon my-1" href="#">
                <img src="img/blog/recent-4.jpg">
                <div>
                    <h4>The personality trait that makes...</h4>
                    <p class="blog__date"><span class="blog__categorie">Fashion</span> - May 19, 2019</p>
                </div>
            </a>
        </div>

        <div class="mb-2">
            <h3 class="title-2">Product Tags</h3>

            <a class="btn__box" href="#">Towel</a>
            <a class="btn__box" href="#">Shoes</a>
            <a class="btn__box" href="#">Coat</a>
            <a class="btn__box" href="#">Dresses</a>
            <a class="btn__box" href="#">Backpack</a>
        </div>
    </div>

    <div class="grid grid--col-2">
        <div>
            <img src="img/blog/blog-1.jpg">
            <a href="/blog_details"><h3 class="blog__title">The personality trait that makes people happier</h3></a>
            <p class="blog__date"><span class="blog__categorie">Travel</span> - May 19, 2019</p>
        </div>

        <div>
            <img src="img/blog/blog-2.jpg">
            <a href="/blog_details"><h3 class="blog__title">This was one of our first days in hawaii last week</h3></a>
            <p class="blog__date"><span class="blog__categorie">Fasion</span> - May 19, 2019</p>
        </div>

        <div>
            <img src="img/blog/blog-3.jpg">
            <a href="/blog_details"><h3 class="blog__title">Happppppy New Year! I know i am a little on this post</h3></a>
            <p class="blog__date"><span class="blog__categorie">Fashion</span> - May 19, 2019</p>
        </div>

        <div>
            <img src="img/blog/blog-4.jpg">
            <a href="/blog_details"><h3 class="blog__title">Absolute collection. The lancome team has been one...</h3></a>
            <p class="blog__date"><span class="blog__categorie">Model</span> - May 19, 2019</p>
        </div>

        <div>
            <img src="img/blog/blog-5.jpg">
            <a href="/blog_details"><h3 class="blog__title">Writing has always been kind of therapeutic for me</h3></a>
            <p class="blog__date"><span class="blog__categorie">Fashion</span> - May 19, 2019</p>
        </div>

        <div>
            <img src="img/blog/blog-6.jpg">
            <a href="/blog_details"><h3 class="blog__title">The personality trait that makes people happier</h3></a>
            <p class="blog__date"><span class="blog__categorie">Travel</span> - May 19, 2019</p>
        </div>
    </div>
</section>