<section class="blog-details container">
    <div class="details-title">
        <h2>The Personality Trait That Makes People Happier</h2>
        <p><span>Travel</span> - May 19, 2019</p>
        <img src="img/blog/blog-detail.jpg">
    </div>

    <div class="details-quote">
        <p>
            Psum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Ut enim ad minim veniam, quis nostrud exercitation
            ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore 
            et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate.
        </p>
        <blockquote>
            “ Technology is nothing. What's important is that you have a faith in people, that they're basically good and smart, and if you give them tools, they'll do wonderful things with them.” - <span>STEVEN JOBS</span>
        </blockquote>
    </div>

    <div class="details-img">
        <img src="img/blog/blog-detail-1.jpg">
        <img src="img/blog/blog-detail-2.jpg">
        <img src="img/blog/blog-detail-3.jpg">
    </div>

    <p>
        Sum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi
        ut aliquip ex ea commodo consequat. Duis aute irure Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad 
        minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate.
    </p>

    <div class="details-social">
        <p>
            <i class="fa fa-tags"></i>
            <span>Travel</span>
            <span>Beauty</span>
            <span>Fashion</span>
        </p>

        <p>
            Share:
            <a href="#"><i class="fab fa-facebook-f"></i></a>
            <a href="#"><i class="fab fa-twitter"></i></a>
            <a href="#"><i class="fab fa-google-plus"></i></a>
            <a href="#"><i class="fab fa-instagram"></i></a>
            <a href="#"><i class="fab fa-youtube"></i></a>
        </p>
    </div>

    <div class="details-slider">
        <a href="#">
            <img src="img/blog/prev-blog.png">
            <div class="prev">
                <span>Previus Post:</span>
                <h4>The personality trait that makes people happier</h4>
            </div>
        </a>

        <a href="#">      
            <div class="next">
                <span>Next Post:</span>
                <h4>The personality trait that makes people happier</h4>
            </div>
            <img src="img/blog/next-blog.png">
        </a>
    </div>

    <div class="details-post">
        <img src="img/blog/post-by.png">

        <div>
            <h4>Shane Lynch</h4>
            <p>
                Aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit 
                in voluptate velit esse cillum bore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud amodo
            </p>
        </div>
    </div>

    <div class="details-comment">
        <h3>Leave a comment</h3>

        <form>
            <div>
                <input type="text" placeholder="Name">
                <input type="email" placeholder="Email">
            </div>

            <textarea rows="6" placeholder="Messages"></textarea>
            <button type="submit">Send Message</button>
        </form>
    </div>
</section>