<section class="page container">
    <i></i><a href="/">Home</a>
    <span>></span> Blog
</section>

<section class="blog blog-blog container">
    <div class="blog__content">
        <div>
            <img src="img/blog/blog-1.jpg">
            <a href="blog-details.html"><h3>The personality trait that makes people happier</h3></a>
            <p><span>Travel</span> - May 19, 2019</p>
        </div>

        <div>
            <img src="img/blog/blog-2.jpg">
            <a href="blog-details.html"><h3>This was one of our first days in hawaii last week</h3></a>
            <p><span>Fasion</span> - May 19, 2019</p>
        </div>

        <div>
            <img src="img/blog/blog-3.jpg">
            <a href="blog-details.html"><h3>Happppppy New Year! I know i am a little on this post</h3></a>
            <p><span>Fashion</span> - May 19, 2019</p>
        </div>

        <div>
            <img src="img/blog/blog-4.jpg">
            <a href="blog-details.html"><h3>Absolute collection. The lancome team has been one...</h3></a>
            <p><span>Model</span> - May 19, 2019</p>
        </div>

        <div>
            <img src="img/blog/blog-5.jpg">
            <a href="blog-details.html"><h3>Writing has always been kind of therapeutic for me</h3></a>
            <p><span>Fashion</span> - May 19, 2019</p>
        </div>

        <div>
            <img src="img/blog/blog-6.jpg">
            <a href="blog-details.html"><h3>The personality trait that makes people happier</h3></a>
            <p><span>Travel</span> - May 19, 2019</p>
        </div>
    </div>

    <div class="blog__aside">
        <div class="aside-search">
            <h3>Search</h3>
            <div>
                <input type="text" placeholder="Search...">
                <button type="submit"><i class="fas fa-search"></i></button>
            </div>
        </div>

        <div class="aside-cat">
            <h3>Categories</h3>

            <ul>
                <li><a href="#">Fashion</a></li>
                <li><a href="#">Travel</a></li>
                <li><a href="#">Picnic</a></li>
                <li><a href="#">Model</a></li>
            </ul>
        </div>

        <div class="aside-post">
            <h3>Recent Post</h3>

            <a href="#">
                <img src="img/blog/recent-1.jpg">
                <div>
                    <h4>The personality trait that makes...</h4>
                    <p><span>Fashion</span> - May 19, 2019</p>
                </div>
            </a>

            <a href="#">
                <img src="img/blog/recent-2.jpg">
                <div>
                    <h4>The personality trait that makes...</h4>
                    <p><span>Fashion</span> - May 19, 2019</p>
                </div>
            </a>

            <a href="#">
                <img src="img/blog/recent-3.jpg">
                <div>
                    <h4>The personality trait that makes...</h4>
                    <p><span>Fashion</span> - May 19, 2019</p>
                </div>
            </a>

            <a href="#">
                <img src="img/blog/recent-4.jpg">
                <div>
                    <h4>The personality trait that makes...</h4>
                    <p><span>Fashion</span> - May 19, 2019</p>
                </div>
            </a>
        </div>

        <div class="aside-tags">
            <h3>Product Tags</h3>

            <a href="#">Towel</a>
            <a href="#">Shoes</a>
            <a href="#">Coat</a>
            <a href="#">Dresses</a>
            <a href="#">Backpack</a>
        </div>
    </div>
</section>