<section class="link-back page__inner">
    <a class="link-back__btn" href="/">Home</a>
    <span class="mx-0-5">></span>
    <a class="link-back__btn" href="/">Blog</a>
    <span class="mx-0-5">></span> Blog Details
</section>

<section class="page__inner page__section">
    <div class="page--center">
        <h2 class="blog__title">The Personality Trait That Makes People Happier</h2>
        <p class="blog__date mb-2"><span class="blog__categorie">Travel</span> - May 19, 2019</p>
        <img src="img/blog/blog-detail.jpg">
    </div>

    <div>
        <p class="my-1">
            Psum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Ut enim ad minim veniam, quis nostrud exercitation
            ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore 
            et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate.
        </p>
        <blockquote class="blog__quote">
            “ Technology is nothing. What's important is that you have a faith in people, that they're basically good and smart, and if you give them tools, they'll do wonderful things with them.” - <span>STEVEN JOBS</span>
        </blockquote>
    </div>

    <div class="grid grid--col-3">
        <img src="img/blog/blog-detail-1.jpg">
        <img src="img/blog/blog-detail-2.jpg">
        <img src="img/blog/blog-detail-3.jpg">
    </div>

    <p class="my-1">
        Sum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi
        ut aliquip ex ea commodo consequat. Duis aute irure Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad 
        minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate.
    </p>

    <div class="blog--border-bot flex py-2">
        <p>
            <i class="fa fa-tags blog__icon"></i>
            <span class="mx-0-5">Travel</span>
            <span class="mx-0-5">Beauty</span>
            <span class="mx-0-5">Fashion</span>
        </p>

        <p>
            Share:
            <a class="link" href="#"><i class="fab fa-facebook-f fa-lg"></i></a>
            <a class="link" href="#"><i class="fab fa-twitter fa-lg"></i></a>
            <a class="link" href="#"><i class="fab fa-google-plus fa-lg"></i></a>
            <a class="link" href="#"><i class="fab fa-instagram fa-lg"></i></a>
            <a class="link" href="#"><i class="fab fa-youtube fa-lg"></i></a>
        </p>
    </div>

    <div class="grid grid--col-2 py-2">
        <a class="grid grid--icon" href="#">
            <img src="img/blog/prev-blog.png">
            <div>
                <span class="blog--light">Previus Post:</span>
                <h4>The personality trait that makes people happier</h4>
            </div>
        </a>

        <a class="grid grid--icon-inverse" href="#">      
            <div class="align-right">
                <span class="blog--light">Next Post:</span>
                <h4>The personality trait that makes people happier</h4>
            </div>
            <img src="img/blog/next-blog.png">
        </a>
    </div>

    <div class="grid grid--icon box box--size-lg box--rounded mb-2">
        <img src="img/blog/post-by.png">

        <div>
            <h4>Shane Lynch</h4>
            <p>
                Aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit 
                in voluptate velit esse cillum bore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud amodo
            </p>
        </div>
    </div>

    <div>
        <h3 class="title-2">Leave a comment</h3>

        <form>
            <div class="grid grid--col-2">
                <input class="input my-1" type="text" placeholder="Name">
                <input class="input my-1" type="email" placeholder="Email">
            </div>

            <textarea class="input my-1" rows="6" placeholder="Messages"></textarea>
            <button class="btn btn--rounded" type="submit">Send Message</button>
        </form>
    </div>
</section>