<section class="cadastro_produto container">
  <div>
    <h2>Cadastro de Produtos</h2>
    <form method="post" action="/registrar_produto">
      <input type="text" name="img" placeholder="Coloque o link da imagem">
      <input type="text" name="nome" placeholder="Nome">
      <input type="number" name="preco" min="1" placeholder="$10.00">
      <textarea rows="6" name="descricao" placeholder="Escreva uma descrição para o produto"></textarea>

      <div class="selects">
        <select name="tamanho">
          <option value="s">S</option>
          <option value="m">M</option>
          <option value="l">L</option>
          <option value="xs">XS</option>
        </select>

        <select name="tag">
          <option value="towel">Towel</option>
          <option value="shoes">Shoes</option>
          <option value="coat">Coat</option>
          <option value="dress">Dress</option>
          <option value="backpack">Backpack</option>
        </select>

        <select name="categoria">
          <option value="men">Men</option>
          <option value="woman">Woman</option>
          <option value="kids">Kids</option>
        </select>
      </div>

      <button type="submit">Cadastrar Produto</button>
    </form>
  </div>
</section>