<section class="link-back page__inner">
    <a class="link-back__btn" href="/">Home</a>
    <span class="mx-0-5">></span>
    <a class="link-back__btn" href="/">Shop</a>
    <span class="mx-0-5">></span> Checkout
</section>

<section class="page__inner page__section grid grid--col-2">
    <div>
        <a class="checkout__btn" href="/login">Click Here To Login</a>

        <h3 class="title-2">Billing Details</h3>

        <form>
            <div class="grid grid--col-2">
                <div>
                    <label class="my-1 d-inline-block">First Name<span>*</span></label>
                    <input class="input" type="text">
                </div>
                
                <div>
                    <label class="my-1 d-inline-block">Last Name<span>*</span></label>
                    <input class="input" type="text">
                </div>
            </div>

            <label class="my-1 d-inline-block">Company Name</label>
            <input class="input" type="text">

            <label class="my-1 d-inline-block">Country<span>*</span></label>
            <input class="input" type="text">

            <label class="my-1 d-inline-block">Street Address<span>*</span></label>
            <input class="input" type="text">

            <label class="my-1 d-inline-block">Postcode / ZIP (optional)</label>
            <input class="input" type="text">

            <label class="my-1 d-inline-block">Town / City<span>*</span></label>
            <input class="input" type="text">

            <div class="grid grid--col-2">
                <div>
                    <label class="my-1 d-inline-block">Email Address<span>*</span></label>
                    <input class="input" type="email">
                </div>

                <div>
                    <label class="my-1 d-inline-block">Phone<span>*</span></label>
                    <input class="input" type="tel">
                </div>
            </div>

            <label class="my-1 d-inline-block">
                <input type="checkbox"> Create an account?
            </label>
        </form>
    </div>

    <div>
        <input class="checkout__btn" type="text" placeholder="Enter Your Coupon Code">

        <h3 class="title-2">Your Order</h3>

        <div class="box">
            <table class="table">
                <tr>
                    <th class="table--align-left">Product</th>
                    <th class="table--align-right">Total</th>
                </tr>
                
                <?php if($this->view->produtos_cart != '') { ?>
                    <?php foreach($this->view->produtos_cart as $produto) { ?>
                        <tr>
                            <td><?= $produto['nome'] ?> X <?= $produto['quantidade'] ?></td>
                            <td class="table--align-right">$<span class="re-price"><?= $produto['preco'] * $produto['quantidade'] ?></span>.00</td>
                        </tr>
                    <?php } ?>
                <?php } ?>    

                <tr>
                    <td>Subtotal</td>
                    <td class="table--align-right">$<span class="price-total"></span>.00</td>
                </tr>

                <tr>
                    <td>Total</td>
                    <td class="table--align-right">$<span class="price-total"></span>.00</td>
                </tr>
            </table>

            <div class="my-1">
                <label class="input__label">
                    <input type="radio" name="payment"> Cheque Payment
                </label>

                <label class="input__label">
                    <input type="radio" name="payment"> Paypal
                </label>
            </div>

            <div class="page--center my-1">
                <button class="btn btn--bg-black">Place Order</button>
            </div>
        </div>
    </div>
</section>