<section class="link-back page__inner">
    <a class="link-back__btn" href="/">Home</a>
    <span class="mx-0-5">></span> Contact
</section>

<section class="contact container">
    <div>
        <h3>Contact Us</h3>
        <p>
            Contrary to popular belief, Lorem Ipsum is simply random text. 
            It has roots in a piece of classical Latin literature from 45 BC, maki years old.  
        </p>

        <div class="contact-addr">
            <i class="fas fa-map-marker-alt"></i>
            <div>
                <p>Address: </p>
                <address>60-49 Road 11378 New York</address>
            </div>
        </div>

        <div class="contact-addr">
            <i class="fas fa-mobile-alt"></i>
            <div>
                <p>Phone: </p>
                <address>+65 11.188.888</address>
            </div>
        </div>

        <div class="contact-addr">
            <i class="fas fa-envelope"></i>
            <div>
                <p>Email: </p>
                <address>hellocolorlib@gmail.com</address>
            </div>
        </div>
    </div>

    <div class="contact__message">
        <h3>Leave A Comment</h3>
        <p>Our staff will call back later and answer your questions.</p>

        <div>
            <input type="text" placeholder="Your Name">
            <input type="text" placeholder="Your Email">
        </div>

        <textarea rows="5" placeholder="Your Message"></textarea>

        <button type="submit"> Send Message</button>
    </div>
</section>