<section class="link-back page__inner">
    <a class="link-back__btn" href="/">Home</a>
    <span class="mx-0-5">></span> Contact
</section>

<section class="page__inner page__section grid grid--col-2">
    <div>
        <h3 class="title-2">Contact Us</h3>
        <p>
            Contrary to popular belief, Lorem Ipsum is simply random text. 
            It has roots in a piece of classical Latin literature from 45 BC, maki years old.  
        </p>

        <div class="grid grid--icon box__shadow my-1">
            <i class="fas fa-map-marker-alt fa-2x grid--center-self"></i>
            <div>
                <p>Address: </p>
                <address>60-49 Road 11378 New York</address>
            </div>
        </div>

        <div class="grid grid--icon box__shadow my-1">
            <i class="fas fa-mobile-alt fa-2x grid--center-self"></i>
            <div>
                <p>Phone: </p>
                <address>+65 11.188.888</address>
            </div>
        </div>

        <div class="grid grid--icon box__shadow my-1">
            <i class="fas fa-envelope fa-2x grid--center-self"></i>
            <div>
                <p>Email: </p>
                <address>hellocolorlib@gmail.com</address>
            </div>
        </div>
    </div>

    <div class="contact__message">
        <h3 class="title-2">Leave A Comment</h3>
        <p>Our staff will call back later and answer your questions.</p>

        <div class="grid grid--col-2">
            <input class="input my-1" type="text" placeholder="Your Name">
            <input class="input my-1" type="text" placeholder="Your Email">
        </div>

        <textarea class="input my-1" rows="5" placeholder="Your Message"></textarea>

        <button class="btn btn--rounded" type="submit"> Send Message</button>
    </div>
</section>