<section class="link-back page__inner">
    <a class="link-back__btn" href="/">Home</a>
    <span class="mx-0-5">></span> Faqs
</section>


<section class="page__inner page__section">
    <div class="my-1">
        <button class="faq__btn"><span class="fas fa-plus faq__icon"></span> Is There Anything i should bring?</button>
        <p class="faq__text">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
        </p>
    </div>

    <div class="my-1">
        <button class="faq__btn"><span class="fas fa-plus faq__icon"></span> Where Can i Find Market Research Reports?</button>
        <p class="faq__text">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
        </p>
    </div>

    <div class="my-1">
        <button class="faq__btn"><span class="fas fa-plus faq__icon"></span> Where Can i find the wall street Journal?</button>
        <p class="faq__text">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
        </p>
    </div>
</section>