<section class="banner">
    <div class="page__inner">
        <div class="banner__content center-y">
            <p class="title__tag"><span>Bag, Kids</span></p>
            <h1 class="title">Black Friday</h1>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
                incididunt ut labore et dolore
            </p>
            <a class="btn my-1" href="#">Shop now</a>
        </div>
    </div>         
</section>

<section class="page__inner page__section grid grid--col-3">
    <div class="pos-rel box--hover">
        <img src="img/banner-1.jpg">
        <span class="center-xy box__outline">Men's</span>
    </div>

    <div class="pos-rel box--hover">
        <img src="img/banner-2.jpg">
        <span class="center-xy box__outline">Women's</span>
    </div>

    <div class="pos-rel box--hover">
        <img src="img/banner-3.jpg">
        <span class="center-xy box__outline">Kids's</span>
    </div>
</section>

<section class="grid grid--col-1-3 page__inner">
    <div class="img img--women">
        <div class="center-xy page--center">
            <h3 class="img__title">Women's</h3>
            <a class="img__link" href="#">Discover More</a>
        </div>
    </div>

    <div class="gallery grid--center-self">
        <ul class="page--center mb-2">
            <li class="d-inline-block"><a class="gallery__link gallery__link--active" href="#">Clothings</a></li>
            <li class="d-inline-block"><a class="gallery__link" href="#">HandBag</a></li>
            <li class="d-inline-block"><a class="gallery__link" href="#">Shoes</a></li>
            <li class="d-inline-block"><a class="gallery__link" href="#">Accessories</a></li>
        </ul>

        <div class="swiper-container">
            <div class="swiper-wrapper">
                <div class="product swiper-slide">
                    <div class="product--hover pos-rel">
                        <img src="img/products/women-1.jpg">
                        <span class="product__sale">Sale</span>
                        
                        <div class="product__overlay">
                            <a href="#"><i class="far fa-heart product__icon"></i></a>
                        </div>
                    </div>

                    <div class="page--center my-1">
                        <small class="product__tag">Coat</small>
                        <h4 class="product__name">Pure Pineapple</h4>
                        <p class="product__price">$14.00 <span class="product__price--sale">$35.00</span></p>
                    </div>
                </div>

                <div class="product swiper-slide">
                    <div class="product--hover pos-rel">
                        <img src="img/products/women-2.jpg">
                        <span class="product__sale">Sale</span>
                        
                        <div class="product__overlay">
                            <a href="#"><i class="far fa-heart product__icon"></i></a>
                        </div>
                    </div>

                    <div class="page--center my-1">
                        <small class="product__tag">Coat</small>
                        <h4 class="product__name">Pure Pineapple</h4>
                        <p class="product__price">$14.00 <span class="product__price--sale">$35.00</span></p>
                    </div>
                </div>

                <div class="product swiper-slide">
                    <div class="product--hover pos-rel">
                        <img src="img/products/women-3.jpg">
                        <span class="product__sale">Sale</span>
                        
                        <div class="product__overlay">
                            <a href="#"><i class="far fa-heart product__icon"></i></a>
                        </div>
                    </div>

                    <div class="page--center my-1">
                        <small class="product__tag">Coat</small>
                        <h4 class="product__name">Pure Pineapple</h4>
                        <p class="product__price">$14.00 <span class="product__price--sale">$35.00</span></p>
                    </div>
                </div>

                <div class="product swiper-slide">
                    <div class="product--hover pos-rel">
                        <img src="img/products/women-4.jpg">
                        <span class="product__sale">Sale</span>
                        
                        <div class="product__overlay">
                            <a href="#"><i class="far fa-heart product__icon"></i></a>
                        </div>
                    </div>

                    <div class="page--center my-1">
                        <small class="product__tag">Coat</small>
                        <h4 class="product__name">Pure Pineapple</h4>
                        <p class="product__price">$14.00 <span class="product__price--sale">$35.00</span></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="week container">
    <div class="week__container">
        <div class="week__content">
            <h2>Deal Of The Week</h2>
            <div></div>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed
                do ipsum dolor sit amet, consectetur adipisicing elit
            </p>
            <p><span>$35.00</span> / HanBag</p>
        </div>

        <div class="week__timer">
            <div>
                <p>28</p>
                <span>Days</span>
            </div>

            <div>
                <p>14</p>
                <span>Hrs</span>
            </div>

            <div>
                <p>14</p>
                <span>Mins</span>
            </div>

            <div>
                <p>60</p>
                <span>Secs</span>
            </div>
        </div>

        <a href="#">Shop Now</a>
    </div>
</section>

<section class="grid grid--col-3-1 page__inner">
    <div class="gallery grid--center-self">
        <ul class="page--center mb-2">
            <li class="d-inline-block"><a class="gallery__link gallery__link--active" href="#">Clothings</a></li>
            <li class="d-inline-block"><a class="gallery__link" href="#">HandBag</a></li>
            <li class="d-inline-block"><a class="gallery__link" href="#">Shoes</a></li>
            <li class="d-inline-block"><a class="gallery__link" href="#">Accessories</a></li>
        </ul>

        <div class="swiper-container">
            <div class="swiper-wrapper">
                <div class="product swiper-slide">
                    <div class="product--hover pos-rel">
                        <img src="img/products/man-1.jpg">
                        <span class="product__sale">Sale</span>
                        
                        <div class="product__overlay">
                            <a href="#"><i class="far fa-heart product__icon"></i></a>
                        </div>
                    </div>

                    <div class="page--center my-1">
                        <small class="product__tag">Coat</small>
                        <h4 class="product__name">Pure Pineapple</h4>
                        <p class="product__price">$14.00 <span class="product__price--sale">$35.00</span></p>
                    </div>
                </div>

                <div class="product swiper-slide">
                    <div class="product--hover pos-rel">
                        <img src="img/products/man-2.jpg">
                        <span class="product__sale">Sale</span>
                        
                        <div class="product__overlay">
                            <a href="#"><i class="far fa-heart product__icon"></i></a>
                        </div>
                    </div>

                    <div class="page--center my-1">
                        <small class="product__tag">Coat</small>
                        <h4 class="product__name">Pure Pineapple</h4>
                        <p class="product__price">$14.00 <span class="product__price--sale">$35.00</span></p>
                    </div>
                </div>

                <div class="product swiper-slide">
                    <div class="product--hover pos-rel">
                        <img src="img/products/man-3.jpg">
                        <span class="product__sale">Sale</span>
                        
                        <div class="product__overlay">
                            <a href="#"><i class="far fa-heart product__icon"></i></a>
                        </div>
                    </div>

                    <div class="page--center my-1">
                        <small class="product__tag">Coat</small>
                        <h4 class="product__name">Pure Pineapple</h4>
                        <p class="product__price">$14.00 <span class="product__price--sale">$35.00</span></p>
                    </div>
                </div>

                <div class="product swiper-slide">
                    <div class="product--hover pos-rel">
                        <img src="img/products/man-4.jpg">
                        <span class="product__sale">Sale</span>
                        
                        <div class="product__overlay">
                            <a href="#"><i class="far fa-heart product__icon"></i></a>
                        </div>
                    </div>

                    <div class="page--center my-1">
                        <small class="product__tag">Coat</small>
                        <h4 class="product__name">Pure Pineapple</h4>
                        <p class="product__price">$14.00 <span class="product__price--sale">$35.00</span></p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="img img--men">
        <div class="center-xy page--center">
            <h3 class="img__title">Men's</h3>
            <a class="img__link" href="#">Discover More</a>
        </div>
    </div>
</section>

<section class="collection">
    <div class="collection__itens">
        <img src="img/insta-1.jpg">
        <div>
            <i class="fab fa-instagram"></i>
            <a href="#">colorlib_collection</a>
        </div>
    </div>

    <div class="collection__itens">
        <img src="img/insta-2.jpg">
        <div>
            <i class="fab fa-instagram"></i>
            <a href="#">colorlib_collection</a>
        </div>
    </div>

    <div class="collection__itens">
        <img src="img/insta-3.jpg">
        <div>
            <i class="fab fa-instagram"></i>
            <a href="#">colorlib_collection</a>
        </div>
    </div>

    <div class="collection__itens">
        <img src="img/insta-4.jpg">
        <div>
            <i class="fab fa-instagram"></i>
            <a href="#">colorlib_collection</a>
        </div>
    </div>

    <div class="collection__itens">
        <img src="img/insta-5.jpg">
        <div>
            <i class="fab fa-instagram"></i>
            <a href="#">colorlib_collection</a>
        </div>
    </div>

    <div class="collection__itens">
        <img src="img/insta-6.jpg">
        <div>
            <i class="fab fa-instagram"></i>
            <a href="#">colorlib_collection</a>
        </div>
    </div>
</section>

<section class="blog container">
    <h2>From The Blog</h2>
    <div class="border"></div>

    <div class="blog__container">
        <div>
            <img src="img/latest-1.jpg">
            <span><i class="far fa-calendar"></i>May 4, 2019<i class="far fa-comment"></i>5</span>
            <a href="#"><h3>The Best Street Style From London Fashion Week</h3></a>
            <p>
                Sed quia non numquam modi tempora indunt ut labore et dolore magnam aliquam quaerat
            </p>
        </div>

        <div>
            <img src="img/latest-2.jpg">
            <span><i class="far fa-calendar"></i>May 4, 2019<i class="far fa-comment"></i>5</span>
            <a href="#"><h3>Vogue's Ultimate Guide To Autumn/Winter 2019 Shoes</h3></a>
            <p>
                Sed quia non numquam modi tempora indunt ut labore et dolore magnam aliquam quaerat
            </p>
        </div>

        <div>
            <img src="img/latest-3.jpg">
            <span><i class="far fa-calendar"></i>May 4, 2019<i class="far fa-comment"></i>5</span>
            <a href="#"><h3>How To Brighten Your Wardrobe With A Dash Of Lime</h3></a>
            <p>
                Sed quia non numquam modi tempora indunt ut labore et dolore magnam aliquam quaerat
            </p>
        </div>
    </div>
</section>

<section class="benefit container">
    <div class="benefit__container">
        <div class="benefit__itens">
            <div>
                <img src="img/icon-1.png">
            </div>

            <div>
                <h3>Free Shipping</h3>
                <p>
                    For all order over 99$
                </p>
            </div>
        </div>

        <div class="benefit__itens">
            <div>
                <img src="img/icon-2.png">
            </div>

            <div>
                <h3>Delivery on time</h3>
                <p>
                    If good have prolems
                </p>
            </div>
        </div>

        <div class="benefit__itens">
            <div>
                <img src="img/icon-3.png">
            </div>

            <div>
                <h3>Secure Payment</h3>
                <p>
                    100% secure payment
                </p>
            </div>
        </div>
    </div>
</section>