<section class="hero">
    <div class="container">
        <div class="hero__container">
            <p><span>Bag, Kids</span></p>
            <h1>Black Friday</h1>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
                incididunt ut labore et dolore
            </p>
            <a href="#">Shop now</a>
        </div>
    </div>         
</section>

<section class="banner container">
    <div>
        <img src="img/banner-1.jpg">
        <span>Men's</span>
    </div>

    <div>
        <img src="img/banner-2.jpg">
        <span>Women's</span>
    </div>

    <div>
        <img src="img/banner-3.jpg">
        <span>Kids's</span>
    </div>
</section>

<section class="women container">
    <div class="women__img">
        <div>
            <h3>Women's</h3>
            <a href="#">Discover More</a>
        </div>
    </div>

    <div class="women__menu">
        <ul>
            <li><a class="actived" href="#">Clothings</a></li>
            <li><a href="#">HandBag</a></li>
            <li><a href="#">Shoes</a></li>
            <li><a href="#">Accessories</a></li>
        </ul>

        <div class="women__menu__gallery">
            <div class="gallery-itens">
                <div class="gallery-img">
                    <img src="img/products/women-1.jpg">
                    <span class="sale">Sale</span>
                    
                    <div class="gallery-overlay">
                        <a href="#"><i class="far fa-heart"></i></a>
                    </div>
                </div>

                <div class="gallery-text">
                    <small>Coat</small>
                    <h4>Pure Pineapple</h4>
                    <p>$14.00 <span>$35.00</span></p>
                </div>
            </div>

            <div class="gallery-itens">
                <div class="gallery-img">
                    <img src="img/products/women-2.jpg">
                    
                    <div class="gallery-overlay">
                        <a href="#"><i class="far fa-heart"></i></a>
                    </div>
                </div>

                <div class="gallery-text">
                    <span>Shoes</span>
                    <h4>Guangzhou sweater</h4>
                    <p>$13.00</p>
                </div>
            </div>

            <div class="gallery-itens">
                <div class="gallery-img">
                    <img src="img/products/women-3.jpg">
                    
                    <div class="gallery-overlay">
                        <a href="#"><i class="far fa-heart"></i></a>
                    </div>
                </div>

                <div class="gallery-text">
                    <span>Towel</span>
                    <h4>Pure Pineapple</h4>
                    <p>$34.00</p>
                </div>
            </div>

            <div class="gallery-itens">
                <div class="gallery-img">
                    <img src="img/products/women-4.jpg">
                    
                    <div class="gallery-overlay">
                        <a href="#"><i class="far fa-heart"></i></a>
                    </div>
                </div>

                <div class="gallery-text">
                    <span>Towel</span>
                    <h4>Converse Shoes</h4>
                    <p>$34.00</p>
                </div>
            </div>
        </div>
        <div style="clear: both;"></div>
    </div>
</section>

<section class="week container">
    <div class="week__container">
        <div class="week__content">
            <h2>Deal Of The Week</h2>
            <div></div>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed
                do ipsum dolor sit amet, consectetur adipisicing elit
            </p>
            <p><span>$35.00</span> / HanBag</p>
        </div>

        <div class="week__timer">
            <div>
                <p>28</p>
                <span>Days</span>
            </div>

            <div>
                <p>14</p>
                <span>Hrs</span>
            </div>

            <div>
                <p>14</p>
                <span>Mins</span>
            </div>

            <div>
                <p>60</p>
                <span>Secs</span>
            </div>
        </div>

        <a href="#">Shop Now</a>
    </div>
</section>

<section class="men container">
    <div class="men__menu">
        <ul>
            <li><a class="actived" href="#">Clothings</a></li>
            <li><a href="#">HandBag</a></li>
            <li><a href="#">Shoes</a></li>
            <li><a href="#">Accessories</a></li>
        </ul>

        <div class="men__menu__gallery">
            <div class="gallery-itens">
                <div class="gallery-img">
                    <img src="img/products/man-1.jpg">
                    <span class="sale">Sale</span>
                    
                    <div class="gallery-overlay">
                        <a href="#"><i class="far fa-heart"></i></a>
                    </div>
                </div>

                <div class="gallery-text">
                    <small>Coat</small>
                    <h4>Pure Pineapple</h4>
                    <p>$14.00 <span>$35.00</span></p>
                </div>
            </div>

            <div class="gallery-itens">
                <div class="gallery-img">
                    <img src="img/products/man-2.jpg">
                    
                    <div class="gallery-overlay">
                        <a href="#"><i class="far fa-heart"></i></a>
                    </div>
                </div>

                <div class="gallery-text">
                    <span>Shoes</span>
                    <h4>Guangzhou sweater</h4>
                    <p>$13.00</p>
                </div>
            </div>

            <div class="gallery-itens">
                <div class="gallery-img">
                    <img src="img/products/man-3.jpg">
                    
                    <div class="gallery-overlay">
                        <a href="#"><i class="far fa-heart"></i></a>
                    </div>
                </div>

                <div class="gallery-text">
                    <span>Towel</span>
                    <h4>Pure Pineapple</h4>
                    <p>$34.00</p>
                </div>
            </div>

            <div class="gallery-itens">
                <div class="gallery-img">
                    <img src="img/products/man-4.jpg">
                    
                    <div class="gallery-overlay">
                        <a href="#"><i class="far fa-heart"></i></a>
                    </div>
                </div>

                <div class="gallery-text">
                    <span>Towel</span>
                    <h4>Converse Shoes</h4>
                    <p>$34.00</p>
                </div>
            </div>
        </div>
    </div>

    <div class="men__img">
        <div>
            <h3>Men's</h3>
            <a href="#">Discover More</a>
        </div>
    </div>
</section>

<section class="collection">
    <div class="collection__itens">
        <img src="img/insta-1.jpg">
        <div>
            <i class="fab fa-instagram"></i>
            <a href="#">colorlib_collection</a>
        </div>
    </div>

    <div class="collection__itens">
        <img src="img/insta-2.jpg">
        <div>
            <i class="fab fa-instagram"></i>
            <a href="#">colorlib_collection</a>
        </div>
    </div>

    <div class="collection__itens">
        <img src="img/insta-3.jpg">
        <div>
            <i class="fab fa-instagram"></i>
            <a href="#">colorlib_collection</a>
        </div>
    </div>

    <div class="collection__itens">
        <img src="img/insta-4.jpg">
        <div>
            <i class="fab fa-instagram"></i>
            <a href="#">colorlib_collection</a>
        </div>
    </div>

    <div class="collection__itens">
        <img src="img/insta-5.jpg">
        <div>
            <i class="fab fa-instagram"></i>
            <a href="#">colorlib_collection</a>
        </div>
    </div>

    <div class="collection__itens">
        <img src="img/insta-6.jpg">
        <div>
            <i class="fab fa-instagram"></i>
            <a href="#">colorlib_collection</a>
        </div>
    </div>
</section>

<section class="blog container">
    <h2>From The Blog</h2>
    <div class="border"></div>

    <div class="blog__container">
        <div>
            <img src="img/latest-1.jpg">
            <span><i class="far fa-calendar"></i>May 4, 2019<i class="far fa-comment"></i>5</span>
            <a href="#"><h3>The Best Street Style From London Fashion Week</h3></a>
            <p>
                Sed quia non numquam modi tempora indunt ut labore et dolore magnam aliquam quaerat
            </p>
        </div>

        <div>
            <img src="img/latest-2.jpg">
            <span><i class="far fa-calendar"></i>May 4, 2019<i class="far fa-comment"></i>5</span>
            <a href="#"><h3>Vogue's Ultimate Guide To Autumn/Winter 2019 Shoes</h3></a>
            <p>
                Sed quia non numquam modi tempora indunt ut labore et dolore magnam aliquam quaerat
            </p>
        </div>

        <div>
            <img src="img/latest-3.jpg">
            <span><i class="far fa-calendar"></i>May 4, 2019<i class="far fa-comment"></i>5</span>
            <a href="#"><h3>How To Brighten Your Wardrobe With A Dash Of Lime</h3></a>
            <p>
                Sed quia non numquam modi tempora indunt ut labore et dolore magnam aliquam quaerat
            </p>
        </div>
    </div>
</section>

<section class="benefit container">
    <div class="benefit__container">
        <div class="benefit__itens">
            <div>
                <img src="img/icon-1.png">
            </div>

            <div>
                <h3>Free Shipping</h3>
                <p>
                    For all order over 99$
                </p>
            </div>
        </div>

        <div class="benefit__itens">
            <div>
                <img src="img/icon-2.png">
            </div>

            <div>
                <h3>Delivery on time</h3>
                <p>
                    If good have prolems
                </p>
            </div>
        </div>

        <div class="benefit__itens">
            <div>
                <img src="img/icon-3.png">
            </div>

            <div>
                <h3>Secure Payment</h3>
                <p>
                    100% secure payment
                </p>
            </div>
        </div>
    </div>
</section>