<section class="page container">
    <i></i><a href="/">Home</a>
    <span>></span>
    <a href="/shop">Shop</a>
    <span>></span> Detail
</section>

<section class="product container">
    <div class="product__content">
        <div class="aside-content">
            <div class="product-description">
                <div class="product-img">
                    <img class="img-center" src="<?= $this->view->produto_unico['img'] ?>">
                    <div>
                        <a href="#"><img src="<?= $this->view->produto_unico['img'] ?>"></a>
                        <a href="#"><img src="<?= $this->view->produto_unico['img'] ?>"></a>
                        <a href="#"><img src="<?= $this->view->produto_unico['img'] ?>"></a>
                    </div>
                </div>

                <div class="product-text">
                    <h5>Oranges<i class="far fa-heart"></i></h5>
                    
                    <h3><?= $this->view->produto_unico['nome'] ?></h3>
                    <div class="stars">
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <span>(5)</span>
                    </div>

                    <p><?= $this->view->produto_unico['descricao'] ?></p>

                    <p>$ <?= $this->view->produto_unico['preco'] ?></p>

                    <p>
                        Color 
                        <span></span><span></span><span></span>
                    </p>

                    <div class="size">
                        <a href="#">S</a>
                        <a href="#">M</a>
                        <a href="#">L</a>
                        <a href="#">XS</a>
                    </div>

                    <form method="post" action="/autenticar_cart?id_produto=<?= $this->view->produto_unico['id'] ?>">
                        <div class="product-add">                        
                            <div>                            
                                <button class="btn-sub"><i class="fas fa-minus"></i></button>
                                <input name="quantidade" type="text" value="1">
                                <button class="btn-some"><i class="fas fa-plus"></i></button>
                            </div>
                            <div><button type="submit">Add to cart</a></button></div>                        
                        </div>
                        <?php if(isset($_GET['erro']) && $_GET['erro'] == 1) { ?>
                            <p style="color: red; padding: 1rem 0">Faça login antes de adicionar um produto ao carrinho!!</p>
                        <?php } ?>

                        <?php if(isset($_GET['erro']) && $_GET['erro'] == 2) { ?>
                            <p style="color: red; padding: 1rem 0">O produto ja esta no carrinho!!</p>
                        <?php } ?>
                    </form>

                    <p><span>Categories:</span> More Accessories, Wallets & Cases</p>
                    <p><span>Tags:</span> Clothing, T-shirt, Woman</p>

                    <div class="product-social">
                        <p>Sku : 00<?= $this->view->produto_unico['id'] ?></p>

                        <div>
                            <a href="#"><i class="fab fa-facebook-f"></i></a>
                            <a href="#"><i class="fab fa-twitter"></i></a>
                            <a href="#"><i class="fab fa-linkedin-in"></i></a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="product-spec">
                <div class="pro-links">
                    <ul>
                        <li><a href="#tab1">Description</a></li>
                        <li><a href="#tab2">Specifications</a></li>
                        <li><a href="#tab3">Customer Reviews (<?= count($this->view->comments) ?>)</a></li>
                    </ul>
                </div>

                <div>
                    <div id="tab1">
                        <div class="tab1">
                            <div>
                                <h4>Introduction</h4>
                                <p><?= $this->view->produto_unico['descricao'] ?></p>
                            </div>

                            <div>
                                <img src="<?= $this->view->produto_unico['img'] ?>">
                            </div>
                        </div>
                    </div>

                    <div id="tab2">
                        <table>
                            <tr>
                                <th>Customer Rating</th>
                                <td class="stars">
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <span>(5)</span>
                                </td>
                            </tr>

                            <tr>
                                <th>Price</th>
                                <td>$ <?= $this->view->produto_unico['preco'] ?></td>
                            </tr>

                            <tr>
                                <th>Add to cart</th>
                                <td>+ Add to cart</td>
                            </tr>

                            <tr>
                                <th>Avaibility</th>
                                <td>22 in stock</td>
                            </tr>

                            <tr>
                                <th>Weight</th>
                                <td>1,3kg</td>
                            </tr>

                            <tr>
                                <th>Size</th>
                                <td><?= $this->view->produto_unico['tamanho'] ?></td>
                            </tr>

                            <tr>
                                <th>Color</th>
                                <td><span></span></td>
                            </tr>

                            <tr>
                                <th>Sku</th>
                                <td>00<?= $this->view->produto_unico['id'] ?></td>
                            </tr>
                        </table>
                    </div>

                    <div id="tab3">
                        <div>
                            <h3><?= count($this->view->comments) ?> Comments</h3>
                            <?php foreach($this->view->comments as $comment) { ?>
                                <div class="comment-item">
                                    <img src="img/product-single/avatar-1.png">

                                    <div>
                                        <div class="stars">
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                        </div>
                                        <h4><?= $comment['nome'] ?><span> - <?= $comment['data'] ?></span></h4>
                                        <p><?= $comment['texto'] ?></p>
                                    </div>
                                </div>
                            <?php } ?>                           

                            <div class="comment-rating">
                                <p>Your Rating</p>
                                <div class="stars">
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                </div>
                            </div>
                        </div>                        
                        
                        <div class="comment-details">
                            <h3>Leave a comment</h3>
            
                            <form method="post" action="/comment?id_produto=<?= $this->view->produto_unico['id'] ?>">
                                <textarea name="texto" rows="6" placeholder="Messages"></textarea>
                                <button type="submit">Send Message</button>
                            </form>
                            <?php if(isset($_GET['erro_comment']) && $_GET['erro_comment'] == 'true') { ?>
                                <p style="color: red; padding: 1rem 0;">Faça login antes de deixar um comentario.</p>
                            <?php } ?>
                        </div>
                    </div>
                </div>
            </div>      
        </div>
    </div>

    <div class="produtos-relacionados"><h2>Produtos Relacionados</h2></div>
    <div class="shop__gallery gallery-product">        
        <?php foreach($this->view->produto_relacionado as $produto) { ?>
            <div class="gallery-itens" id="<?= $produto['id'] ?>">
                <div class="gallery-img">
                    <img src="<?= $produto['img'] ?>">
                    
                    <div class="gallery-overlay">
                        <a href="#"><i class="far fa-heart"></i></a>
                    </div>
                </div>

                <div class="gallery-text">
                    <small><?= $produto['tag'] ?></small>
                    <h4><?= $produto['nome'] ?></h4>
                    <p>$<?= $produto['preco'] ?></p>
                </div>
            </div>    
        <?php } ?>                                                                    
    </div>
</section>

<script src="js/produto-id.js"></script>