<section class="link-back page__inner">
    <a class="link-back__btn" href="/">Home</a>
    <span class="mx-0-5">></span>
    <a class="link-back__btn" href="/">Shop</a>
    <span class="mx-0-5">></span> Details
</section>

<section class="page__inner page__section">
    <div class="">
        <div class="">
            <div class="grid grid--col-2 mb-2">
                <div>
                    <img class="mb-2" src="<?= $this->view->produto_unico['img'] ?>">

                    <div class="grid grid--3">
                        <a href="#"><img src="<?= $this->view->produto_unico['img'] ?>"></a>
                        <a href="#"><img src="<?= $this->view->produto_unico['img'] ?>"></a>
                        <a href="#"><img src="<?= $this->view->produto_unico['img'] ?>"></a>
                    </div>
                </div>

                <div class="">
                    
                    
                    <h3 class="product__name flex"><?= $this->view->produto_unico['nome'] ?><i class="far fa-heart"></i></h3>

                    <div class="product__stars">
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                    </div>

                    <p class="my-1"><?= $this->view->produto_unico['descricao'] ?></p>

                    <p class="product__price">$ <?= $this->view->produto_unico['preco'] ?></p>

                    <div class="my-1">
                        <a class="btn__box" href="#">S</a>
                        <a class="btn__box" href="#">M</a>
                        <a class="btn__box" href="#">L</a>
                        <a class="btn__box" href="#">XS</a>
                    </div>

                    <div class="my-1">
                        <form method="post" action="/autenticar_cart?id_produto=<?= $this->view->produto_unico['id'] ?>">
                            <div class="grid grid--col-1-2">                        
                                <div class="pos-rel">                            
                                    <button class="btn btn__input btn__input--left btn-sub"><i class="fas fa-minus"></i></button>
                                    <input class="input align-center" name="quantidade" type="text" value="1">
                                    <button class="btn btn__input btn-some"><i class="fas fa-plus"></i></button>
                                </div>
    
                                <div><button class="btn btn--block" type="submit">Add to cart</a></button></div>                        
                            </div>
    
                            <?php if(isset($_GET['erro']) && $_GET['erro'] == 1) { ?>
                                <p style="color: red; padding: 1rem 0">Faça login antes de adicionar um produto ao carrinho!!</p>
                            <?php } ?>
    
                            <?php if(isset($_GET['erro']) && $_GET['erro'] == 2) { ?>
                                <p style="color: red; padding: 1rem 0">O produto ja esta no carrinho!!</p>
                            <?php } ?>
                        </form>
                    </div>

                    <p><span class="product--bold">Categories:</span> More Accessories, Wallets & Cases</p>
                    <p class="mb-2"><span class="product--bold">Tags:</span> Clothing, T-shirt, Woman</p>

                    <div class="flex">
                        <p><span class="product--bold">Sku:</span> 00<?= $this->view->produto_unico['id'] ?></p>

                        <div>
                            <a class="link" href="#"><i class="fab fa-facebook-f"></i></a>
                            <a class="link" href="#"><i class="fab fa-twitter"></i></a>
                            <a class="link" href="#"><i class="fab fa-linkedin-in"></i></a>
                        </div>
                    </div>
                </div>
            </div>

            <div>
                <div class="mb-2">
                    <ul class="flex--md flex--content-center">
                        <li><a class="product__links" href="#tab1">Description</a></li>
                        <li><a class="product__links" href="#tab2">Specifications</a></li>
                        <li><a class="product__links" href="#tab3">Customer Reviews (<?= count($this->view->comments) ?>)</a></li>
                    </ul>
                </div>

                <div>
                    <div id="tab1" class="d-none page__section">
                        <div class="grid grid--col-3-1">
                            <div>
                                <h4 class="title-2">Introduction</h4>
                                <p><?= $this->view->produto_unico['descricao'] ?></p>
                            </div>

                            <div>
                                <img src="<?= $this->view->produto_unico['img'] ?>">
                            </div>
                        </div>
                    </div>

                    <div id="tab2" class="d-none page__section">
                        <table class="table">
                            <tr>
                                <th class="table--align-left">Customer Rating</th>
                                <td class="product__stars table--align-right">
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                </td>
                            </tr>

                            <tr>
                                <th class="table--align-left">Price</th>
                                <td class="product__price table--align-right">$ <?= $this->view->produto_unico['preco'] ?></td>
                            </tr>

                            <tr>
                                <th class="table--align-left">Avaibility</th>
                                <td class="table--align-right">22 in stock</td>
                            </tr>

                            <tr>
                                <th class="table--align-left">Weight</th>
                                <td class="table--align-right">1,3kg</td>
                            </tr>

                            <tr>
                                <th class="table--align-left">Size</th>
                                <td class="table--align-right"><?= $this->view->produto_unico['tamanho'] ?></td>
                            </tr>

                            <tr>
                                <th class="table--align-left">Sku</th>
                                <td class="table--align-right">00<?= $this->view->produto_unico['id'] ?></td>
                            </tr>
                        </table>
                    </div>

                    <div id="tab3" class="d-none page__section">
                        <div>
                            <h3 class="title-2"><?= count($this->view->comments) ?> Comments</h3>
                            <?php foreach($this->view->comments as $comment) { ?>
                                <div class="grid grid--icon mb-2">
                                    <img src="img/product-single/avatar-1.png">

                                    <div>
                                        <div class="product__stars">
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                        </div>
                                        <h4><?= $comment['nome'] ?><span> | <?= $comment['data_comment'] ?></span></h4>
                                        <p><?= $comment['texto'] ?></p>
                                    </div>
                                </div>
                            <?php } ?>                           

                            <div class="mb-2">
                                <p>Your Rating</p>
                                <div class="product__stars">
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                </div>
                            </div>
                        </div>                        
                        
                        <div>
                            <h3 class="title-2">Leave a comment</h3>
            
                            <form method="post" action="/comment?id_produto=<?= $this->view->produto_unico['id'] ?>">
                                <textarea class="input mb-2" name="texto" rows="6" placeholder="Messages"></textarea>
                                <button class="btn" type="submit">Send Message</button>
                            </form>
                            <?php if(isset($_GET['erro_comment']) && $_GET['erro_comment'] == 'true') { ?>
                                <p style="color: red; padding: 1rem 0;">Faça login antes de deixar um comentario.</p>
                            <?php } ?>
                        </div>
                    </div>
                </div>
            </div>      
        </div>
    </div>

    <h2 class="title title--center">Produtos Relacionados</h2>

    <div class="grid grid--col-4">        
        <?php foreach($this->view->produto_relacionado as $produto) { ?>
            <div class="product" id="<?= $produto['id'] ?>">
                <div class="product--hover pos-rel">
                    <img class="product__img" src="<?= $produto['img'] ?>">
                    
                    <div class="product__overlay">
                        <a href="#"><i class="far fa-heart product__icon product__icon--white"></i></a>
                    </div>
                </div>

                <small class="product__tag"><?= $produto['tag'] ?></small>
                <h4 class="product__name"><?= $produto['nome'] ?></h4>
                <p class="product__price">$<?= $produto['preco'] ?></p>
            </div>    
        <?php } ?>                                                                    
    </div>
</section>

<script src="js/produto-id.js"></script>