<section class="link-back page__inner">
    <a class="link-back__btn" href="/">Home</a>
    <span class="mx-0-5">></span> Register
</section>

<section class="page__inner">
    <div class="page__user page__section">
        <form method="post" action="/registrar">
            <h3 class="title title--center">Register</h3>

            <label class="my-1 d-inline-block">Nome *</label>
                <input class="input" name="nome" type="text">

            <label class="my-1 d-inline-block">Email address *</label>
                <input class="input" name="email" type="text">

            <label class="my-1 d-inline-block">Password *</label>
                <input class="input" name="pass" type="password">

            <label class="my-1 d-inline-block">Confirm Password *</label>
                <input class="input" name="re-pass" type="password">
            
            <button class="btn btn--block user__btn my-1" type="submit">Register</button>

            <?php if($this->view->erroCadastro) { ?>
                <small>
                    *Erro ao tentar realizar o cadastro, verifique se os campos foram preenchidos corretamente.
                </small>
            <?php } ?>

            <div class="page--center my-1"><a class="user__link" href="/login">Or login</a></div>
        </form>
    </div>
</section>