<section class="link-back page__inner">
    <a class="link-back__btn" href="/">Home</a>
    <span class="mx-0-5">></span>
    <a class="link-back__btn" href="/">Shop</a>
    <span class="mx-0-5">></span> Shopping Cart
</section>

<section class="page__inner page__section">
    <?php if($this->view->produtos_cart != '') { ?>
        <div class="mb-2">
            <table class="table table--center">
                <thead>
                    <tr>
                        <th>Image</th>
                        <th>Product Name</th>
                        <th>Price</th>
                        <th>Quantity</th>
                        <th>Total</th>
                        <th>x</th>
                    </tr>
                </thead>

                <tbody>
                    <?php foreach($this->view->produtos_cart as $produto) { ?>
                        <tr class="">
                            <td><img class="table__image" src="<?= $produto['img'] ?>"></td>
                            <td><?= $produto['nome'] ?></td>
                            <td class="text-primary">$<span class="price"><?= $produto['preco'] ?></span></td>
                            <td class="quantidade_produto"><?= $produto['quantidade'] ?></td>
                            <td class="text-primary">$<span class="re-price">60</span>.00</td>
                            <td><a href="/remover_cart?id_produto=<?= $produto['id_produto'] ?>" class="btn-remove text-red">x</a></td>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
    <?php } else { ?>
        <h2 class="title mb-2">Não tem produtos no carrinho</h2>
    <?php } ?>

    <div class="grid grid--col-2">
        <div class="discount">
            <a class="btn btn__transparent" href="/shop">Continue Shopping</a>
            <a class="btn btn--bg-black mb-2" href="/shopping_cart">Update Cart</a>

            <h3 class="title-2">Discount Codes</h3>

            <div class="pos-rel">
                <input class="input" type="text" placeholder="Enter your codes">
                <button class="btn btn__input">Apply</button>
            </div>
        </div>

        <div class="">
            <div class="box box__color">
                <p class="flex my-1">Subtotal <span class="price-abs">$<span class="price-total"></span>.00</span></p>
                <p class="flex my-1">Total <span class="price-abs text-primary">$<span class="price-total"></span>.00</span></p>
            </div>

            <a class="btn btn--block btn--bg-black" href="/checkout">Proceed to check out</a>
        </div>
    </div>
</section>