<html>
	<head>
		<meta charset="utf-8" />
		<title>E-commerce Fashi</title>
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">	

		<!-- <link rel="stylesheet" type="text/css" href="/css/style.css"> -->
		<link rel="stylesheet" type="text/css" href="/css/main.css">

		<!-- JQuery -->
		<script src="https://code.jquery.com/jquery-3.4.1.min.js"
		integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
        crossorigin="anonymous"></script>
        
        <script src="js/menu.js"></script>
        <script src="js/cart-total.js"></script>
        <script src="js/dropdown.js"></script>
        <script src="js/dropdown-bag.js"></script>
        <script src="js/slider.js"></script>
        <script src="js/dropdown-faq.js"></script>
        <script src="js/product-spec.js"></script>
        
	</head>

	<body>
		<header class="header">
            <div class="header__first">
                <div class="container">
                    <div class="header__addr">
                        <i class="fas fa-envelope"></i><span>hello.colorlib@gmail.com</span>
                        <i class="fas fa-phone"></i><span>+65 11.188.888</span>
                    </div>

                    <div class="header__login">
                        <div class="header__login__social">
                            <a href="#"><i class="fab fa-facebook-f"></i></a>
                            <a href="#"><i class="fab fa-twitter"></i></a>
                            <a href="#"><i class="fab fa-linkedin-in"></i></a>
                            <a href="#"><i class="fab fa-pinterest"></i></a>
                        </div>

                        <div>
                            <select>
                                <option value="english"><img src="img/flag-1.jpg">English</option>
                                <option value="german"><img src="img/flag-2.jpg">German</option>
                            </select> 
                            
                            <div>
                                <?php if($this->view->autentica == false) { ?>
                                    <a href="/login">Login</a>
                                <?php } ?>
                                
                                <?php if($this->view->autentica) { ?>
                                    <ul class="user-drop">
                                        <li>
                                            <i class="fas fa-user"></i><span><?= $_SESSION['nome'] ?></span>
                                            <ul>
                                                <li>
                                                    <?php if($_SESSION['perfil_id'] == 1) { ?>
                                                        <a href="/cadastro_produto">Cadastrar Produtos</a>
                                                    <?php } ?>
                                                </li>
                                                <li><a href="/sair">Sair</a></li>
                                            </ul>
                                        </li>
                                    </ul>                 
                                <?php } ?>
                            </div>                        
                        </div>
                    </div>
                    <div style="clear: both;"></div>
                </div>              
            </div>
            
            <div class="header__search container">
                <div class="logo">
                    <a href="#">Fashi<span>.</span></a>
                </div>

                <div class="search">
                    <input type="text" placeholder="What do you need?" />
                    <button type="submit"><i class="fas fa-search"></i></button>
                </div>

                <div class="bag">
                    <div>
                        <a class="icons" href="#"><i class="far fa-heart"><span>1</span></i></a>
                        <a class="icons bag-icon" href="#"><i class="fas fa-shopping-bag"><span>3</span></i></a>
                        <span>$150.00</span>
                        
                        <div class="bag-dropdown">
                            <div class="bag-itens">
                                <img src="img/select-product-1.jpg">
                                <div>
                                    <p><span>$60.00 x 1</span></p>
                                    <p>Kabino Bedside Table</p>
                                </div>
                                <div><a href="#">X</a></div>
                            </div>

                            <div class="bag-total">
                                <p>Total: <span>$120.00</span></p>
                                <button>View Card</button>
                                <button>Check Out</button>
                            </div>
                        </div>
                    </div>
                    
                    <div class="btn-menu">
                        <button><span>Menu</span><i class="fas fa-bars"></i></button>
                    </div>
                </div>
            </div>

            <nav class="header__navbar">
                <div class="navbar__container container">
                    <div class="department">
                        <ul>
                            <li><a class="department__btn" href="#"><i class="fas fa-bars"></i>All Departments<i class="fas fa-arrow-down"></i></a>
                                <ul class="department__dropdown">
                                    <li><a href="#">Men’s Clothing</a></li>
                                    <li><a href="#">Underwear</a></li>
                                    <li><a href="#">Kid's Clothing</a></li>
                                    <li><a href="#">Brand Fashion</a></li>
                                    <li><a href="#">Accessories/Shoes</a></li>
                                    <li><a href="#">Luxury Brands</a></li>
                                    <li><a href="#">Brand Outdoor Apparel</a></li>
                                </ul>
                            </li>                      
                        </ul>
                    </div>

                    <ul class="nav-menu">
                        <li><a href="/">Home</a></li>
                        <li><a href="/shop">Shop</a></li>
                        <li class="dropdown-link"><a href="#">Collection<i class="fas fa-arrow-right"></i></a>
                            <ul class="dropdown">
                                <li><a href="#">Men's</a></li>
                                <li><a href="#">Women's</a></li>
                                <li><a href="#">Kid's</a></li>
                            </ul>
                        </li>
                        <li><a href="/blog">Blog</a></li>
                        <li><a href="/contact">Contact</a></li>
                        <li class="dropdown-link"><a class="last" href="#">Pages<i class="fas fa-arrow-right"></i></a>
                            <ul class="dropdown">
                                <li><a href="/blog_details">Blog Details</a></li>
                                <li><a href="/shopping_cart">Shopping Cart</a></li>
                                <li><a href="/checkout">Checkout</a></li>
                                <li><a href="/faq">Faq</a></li>

                                <?php if(!$this->view->autentica) { ?>
                                    <li><a href="/register">Register</a></li>
                                    <li><a href="/login">Login</a></li>
                                <?php } ?>
                            </ul>
                        </li>
                    </ul>  
                </div>              
            </nav>
        </header>
		
		<?= $this->content() ?>

		<section class="partner-logo">
            <div class="partner-logo__container container">
                <div>
                    <img src="img/logo-carousel/logo-1.png">
                </div>
                <div>
                    <img src="img/logo-carousel/logo-2.png">
                </div>
                <div>
                    <img src="img/logo-carousel/logo-3.png">
                </div>
                <div>
                    <img src="img/logo-carousel/logo-4.png">
                </div>
                <div>
                    <img src="img/logo-carousel/logo-5.png">
                </div>
            </div>
        </section>

		<footer class="footer">
            <div class="container">
                <div class="footer__content">
                    <div>
                        <a href="#"><h3>Fashi<span>.</span></h3></a>
                        <address>
                            Address: 60-49 Road 11378 New York
                        </address>
                        <address>
                            Phone: +65 11.188.888
                        </address>
                        <address>
                            Email: hello.colorlib@gmail.com
                        </address>
                        <div class="footer-icons">
                            <a href="#"><i class="fab fa-facebook-f"></i></a>
                            <a href="#"><i class="fab fa-twitter"></i></a>
                            <a href="#"><i class="fab fa-linkedin-in"></i></a>
                            <a href="#"><i class="fab fa-pinterest"></i></a>
                        </div>
                    </div>

                    <div>
                        <h3>Information</h3>
                        <ul>
                            <li><a href="#">About Us</a></li>
                            <li><a href="/checkout">Checkout</a></li>
                            <li><a href="/contact">Contact</a></li>
                            <li><a href="#">Serivus</a></li>
                        </ul>
                    </div>

                    <div>
                        <h3>My Account</h3>
                        <ul>
                            <li><a href="">My Account</a></li>
                            <li><a href="/contact">Contact</a></li>
                            <li><a href="/shopping_cart">Shopping Cart</a></li>
                            <li><a href="/shop">Shop</a></li>
                        </ul>
                    </div>

                    <div class="footer-email">
                        <h3>Join Our Newsletter Now</h3>
                        <p>Get E-mail updates about our latest shop and special offers.</p>
                        <div>
                            <input type="email" placeholder="Enter Your Mail">
                            <button type="submit">Subscribe</button>
                        </div>
                    </div>
                </div>

                <div class="footer__copy">
                    <div>
                        <p>Copyright ©2020 All rights reserved | This template is made with  by Colorlib</p>
                    </div>

                    <div class="copy-img">
                        <img src="img/payment-method.png">
                    </div>
                </div>
            </div>
        </footer>
	</body>

</html>