<html>
	<head>
		<meta charset="utf-8" />
		<title>E-commerce Fashi</title>
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">	

        
        <!-- Swiper CSS -->
		<link rel="stylesheet" type="text/css" href="css/swiper.min.css">	
		     
        <link rel="stylesheet" type="text/css" href="/css/main.css">


		<!-- JQuery -->
		<script src="https://code.jquery.com/jquery-3.4.1.min.js"
		integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
        crossorigin="anonymous"></script>

        <!-- Swiper JS -->
		<script src="js/swiper.js"></script>
        
        <script src="js/menu.js"></script>
        <script src="js/cart-total.js"></script>
        <script src="js/dropdown.js"></script>
        <script src="js/dropdown-faq.js"></script>
        <script src="js/product-spec.js"></script>
        
	</head>

	<body>
		<header class="header">
            <div class="top">
                <div class="page__inner">
                    <div class="top__left">
                        <i class="fas fa-envelope"></i><span class="mx-0-5">hello.colorlib@gmail.com</span>
                        <i class="fas fa-phone"></i><span class="mx-0-5">+65 11.188.888</span>
                    </div>

                    <div class="top__right">
                        <div class="top__social">
                            <a class="link" href="#"><i class="fab fa-facebook-f"></i></a>
                            <a class="link" href="#"><i class="fab fa-twitter"></i></a>
                            <a class="link" href="#"><i class="fab fa-linkedin-in"></i></a>
                            <a class="link" href="#"><i class="fab fa-pinterest"></i></a>
                        </div>

                        <div class="top__user">
                            <select class="top__lang">
                                <option value="english"><img src="img/flag-1.jpg">English</option>
                                <option value="german"><img src="img/flag-2.jpg">German</option>
                            </select> 
                            
                            <div class="top__user">
                                <?php if($this->view->autentica == false) { ?>
                                    <a class="link" href="/login">Login</a>
                                <?php } ?>
                                
                                <?php if($this->view->autentica) { ?>
                                    <ul class="flex">
                                        <li class="mx-0-5"><i class="fas fa-user mx-0-5"></i><span><?= $_SESSION['nome'] ?></span></li>
                                        <li class="mx-0-5"><a href="/sair">Sair</a></li>
                                    </ul>                 
                                <?php } ?>
                            </div>                        
                        </div>
                    </div>
                    <div style="clear: both;"></div>
                </div>              
            </div>
            
            <div class="logo page__inner">
                <div class="logo__text">
                    <a class="logo__link" href="#">Fashi<span class="text-primary">.</span></a>
                </div>

                <div class="search">
                    <input class="input" type="text" placeholder="What do you need?" />
                    <button class="btn btn__input" type="submit"><i class="fas fa-search"></i></button>
                </div>

                <div class="bag">
                    <div class="bag--py-0-5 dropdown__hover">
                        <a class="link link--rel" href="#"><i class="far fa-heart"><span class="link__numb">1</span></i></a>
                        <a class="link link--rel" href="/shopping_cart"><i class="fas fa-shopping-bag"><span class="link__numb">3</span></i></a>
                        <span>$150.00</span>
                        
                        <div class="dropdown dropdown__bag dropdown--right">
                            <div class="bag__itens">
                                <img src="img/select-product-1.jpg">
                                <div class="bag__details">
                                    <p><span class="text-primary">$60.00 x 1</span></p>
                                    <p>Kabino Bedside Table</p>
                                </div>
                                <div class="bag__details"><a class="link" href="#">X</a></div>
                            </div>

                            <div class="bag__total text-primary">
                                <p class="flex my-1">Total: <span>$120.00</span></p>
                                <button class="btn btn--bg-black btn--block my-1">View Card</button>
                                <button class="btn btn--block my-1">Check Out</button>
                            </div>
                        </div>
                    </div>
                    
                    <div>
                        <button class="btn btn--size-sm btn__menu">
                            <span>Menu</span>
                            
                            <div class="bar-btn header__link">
                                <span class="bar-btn__line"></span>
                                <span class="bar-btn__line"></span>
                                <span class="bar-btn__line"></span>
                            </div>
                        </button>
                    </div>
                </div>
            </div>

            <nav class="navbar page--bg-darker">
                <div class="grid grid--no-gap grid--col-1-2 page__inner">
                    <div class="navbar__department">
                        <ul>
                            <li class="dropdown__hover"><a class="link__menu link--block" href="#"><i class="fas fa-bars mx-0-5"></i>All Departments<i class="fas fa-arrow-down mx-0-5"></i></a>
                                <ul class="dropdown dropdown--left dropdown--right">
                                    <li><a class="link__menu link__menu--dep" href="#">Men’s Clothing</a></li>
                                    <li><a class="link__menu link__menu--dep" href="#">Underwear</a></li>
                                    <li><a class="link__menu link__menu--dep" href="#">Kid's Clothing</a></li>
                                    <li><a class="link__menu link__menu--dep" href="#">Brand Fashion</a></li>
                                    <li><a class="link__menu link__menu--dep" href="#">Accessories/Shoes</a></li>
                                    <li><a class="link__menu link__menu--dep" href="#">Luxury Brands</a></li>
                                    <li><a class="link__menu link__menu--dep" href="#">Brand Outdoor Apparel</a></li>
                                </ul>
                            </li>                      
                        </ul>
                    </div>

                    <ul class="navbar__menu">
                        <li><a class="link__menu link__menu--nav" href="/">Home</a></li>
                        <li><a class="link__menu link__menu--nav" href="/shop">Shop</a></li>
                        <li class="link--rel btn-dropdown dropdown__hover"><a class="link__menu link__menu--nav" href="#">Collection<i class="fas fa-arrow-right fa-sm mx-0-5"></i></a>
                            <ul class="dropdown dropdown__menu dropdown--right">
                                <li><a class="link__menu link--pl-2 link__menu--nav" href="#">Men's</a></li>
                                <li><a class="link__menu link--pl-2 link__menu--nav" href="#">Women's</a></li>
                                <li><a class="link__menu link--pl-2 link__menu--nav" href="#">Kid's</a></li>
                            </ul>
                        </li>
                        <li><a class="link__menu link__menu--nav" href="/blog">Blog</a></li>
                        <li><a class="link__menu link__menu--nav" href="/contact">Contact</a></li>
                        <li class="link--rel btn-dropdown dropdown__hover"><a class="link__menu link__menu--nav link--no-border"href="#">Pages<i class="fas fa-arrow-right fa-sm mx-0-5"></i></a>
                            <ul class="dropdown dropdown__menu dropdown--right">
                                <li><a class="link__menu link--pl-2 link__menu--nav" href="/blog_details">Blog Details</a></li>
                                <li><a class="link__menu link--pl-2 link__menu--nav" href="/shopping_cart">Shopping Cart</a></li>
                                <li><a class="link__menu link--pl-2 link__menu--nav" href="/checkout">Checkout</a></li>
                                <li><a class="link__menu link--pl-2 link__menu--nav" href="/faq">Faq</a></li>

                                <?php if(!$this->view->autentica) { ?>
                                    <li><a class="link__menu link--pl-2 link__menu--nav" href="/register">Register</a></li>
                                    <li><a class="link__menu link--pl-2 link__menu--nav" href="/login">Login</a></li>
                                <?php } ?>
                            </ul>
                        </li>
                    </ul>  
                </div>              
            </nav>
        </header>
		
		<?= $this->content() ?>

		<section class="page__section page--bg-black">
            <div class="page__inner grid grid--col-5">
                <div class="pos-rel">
                    <img class="center-y" src="img/logo-carousel/logo-1.png">
                </div>

                <div class="pos-rel">
                    <img class="center-y" src="img/logo-carousel/logo-2.png">
                </div>

                <div class="pos-rel">
                    <img class="center-y" src="img/logo-carousel/logo-3.png">
                </div>

                <div class="pos-rel">
                    <img class="center-y" src="img/logo-carousel/logo-4.png">
                </div>

                <div class="pos-rel">
                    <img class="center-y" src="img/logo-carousel/logo-5.png">
                </div>
            </div>
        </section>

		<footer class="page--bg-darker page--text-lighter">
            <div class="page__inner">
                <div class="grid grid--footer py-2">
                    <div>
                        <h3 class="title-2 title--white">Fashi<span class="text-primary">.</span></h3>
                        <address>
                            Address: 60-49 Road 11378 New York
                        </address>

                        <address>
                            Phone: +65 11.188.888
                        </address>

                        <address>
                            Email: hello.colorlib@gmail.com
                        </address>

                        <div>
                            <a class="link__social" href="#"><i class="fab fa-facebook-f"></i></a>
                            <a class="link__social" href="#"><i class="fab fa-twitter"></i></a>
                            <a class="link__social" href="#"><i class="fab fa-linkedin-in"></i></a>
                            <a class="link__social" href="#"><i class="fab fa-pinterest"></i></a>
                        </div>
                    </div>

                    <div>
                        <h3 class="title-2 title--white">Information</h3>
                        <ul>
                            <li><a class="link__inline" href="#">About Us</a></li>
                            <li><a class="link__inline" href="/checkout">Checkout</a></li>
                            <li><a class="link__inline" href="/contact">Contact</a></li>
                            <li><a class="link__inline" href="#">Serivus</a></li>
                        </ul>
                    </div>

                    <div>
                        <h3 class="title-2 title--white">My Account</h3>
                        <ul>
                            <li><a class="link__inline" href="">My Account</a></li>
                            <li><a class="link__inline" href="/contact">Contact</a></li>
                            <li><a class="link__inline" href="/shopping_cart">Shopping Cart</a></li>
                            <li><a class="link__inline" href="/shop">Shop</a></li>
                        </ul>
                    </div>

                    <div>
                        <h3 class="title-2 title--white">Join Our Newsletter Now</h3>
                        <p>Get E-mail updates about our latest shop and special offers.</p>
                        <div class="pos-rel my-1">
                            <input class="input" type="email" placeholder="Enter Your Mail">
                            <button class="btn btn__input" type="submit">Subscribe</button>
                        </div>
                    </div>
                </div>

                <div class="grid grid--autofit page--center py-2">
                    <div>
                        <p>Copyright ©2020 All rights reserved | This template is made with  by Colorlib</p>
                    </div>

                    <div class="grid--self-end">
                        <img src="img/payment-method.png">
                    </div>
                </div>
            </div>
        </footer>

        <script src="js/swiper.min.js" defer></script>
	</body>

</html>